### ISSUE TITLE
ReferenceError: customElements is not defined

### ISSUE THREAD

**Issue by glauberm** [ividjs/ivid#1]
Getting a `ReferenceError: customElements is not defined` on Firefox 60.5.0esr (64-bit).

**Comment by alxpez** [comment]
Your browser isn't compatible with the customElements API (available in FF since v63), check [compatible browser/versions](https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements#Browser_compatibility).

You could either update it (or try on a different one) or add a `customElements` [polyfill](https://github.com/webcomponents/custom-elements), to allow larger compatibility.

Currently `ivid`'s distribution bundle doesn't include any polyfills (aka. it's fully compatible with modern browsers, for older ones... there's some digging to do)
